project_id = "etickkjsiibsftjtbavy"

[functions.purchase]
verify_jwt = false

[functions.approve-topup]
verify_jwt = false

[functions.fetch-usd-rate]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.fetch-provider-services]
verify_jwt = false

[functions.sync-order-status]
verify_jwt = false

[functions.test-api-provider]
verify_jwt = false

[functions.fetch-api-services]
verify_jwt = false

[functions.backfill-custom-fields]
verify_jwt = false

[functions.ai-product-build]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false