project_id = "etickkjsiibsftjtbavy"

[functions.purchase]
verify_jwt = false

[functions.approve-topup]
verify_jwt = false

[functions.fetch-usd-rate]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false